/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_appsync_graphqlEndpoint": "https://lttw7eeiznhztovj2lvhhhhiqi.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-rajpcjvmj5dobheza3c2nvucl4",
    "aws_cognito_identity_pool_id": "us-west-2:c29f4cd4-e89b-45f8-8303-bc2fbd584e21",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_JlaJjelnk",
    "aws_user_pools_web_client_id": "1iiu3jniqil6hi32uri6gav9t5",
    "oauth": {}
};


export default awsmobile;
